server:  
  port: 8200   # HTTP port
  
eureka:
  client:
    enabled: true
  service-url:
    default-zone: http:http://localhost:8761/eureka

logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.piloto: 'DEBUG

